import {
  type BlastRadiusMap,
  BlastRadiusMap as BlastRadiusMapSchema,
  type IncidentContext,
  type IncidentReport,
  IncidentReport as IncidentReportSchema,
  type RecoveryPlan,
  RecoveryPlan as RecoveryPlanSchema,
  SCHEMA_VERSION,
} from '@crown/contracts';
import type { LLMClient, LLMMessage } from './client.js';
import { type FaithfulnessConfig, type FaithfulnessResult, checkFaithfulness } from './faithfulness.js';
import { type PlaybookPassage, retrieve } from './playbook.js';

/**
 * LLM Orchestration Layer (Phase 4; consumes C3, produces C7). ADVISORY ONLY — it can NEVER emit an
 * ActionRecord or an AgentCommand. The blast-radius map is DERIVED from the IncidentContext (not invented
 * by the model). The report + recovery plan are generated by the self-hosted model, grounded by RAG over
 * the IR playbook, and validated by the faithfulness gate before being shipped as authoritative. If the
 * model is unavailable the layer DEGRADES gracefully (detection + containment are unaffected; the report is
 * marked unavailable/queued) — AC-FAIL-01.
 */
export type AnalysisStatus = 'OK' | 'BLOCKED_LOW_FAITHFULNESS' | 'MALFORMED_OUTPUT' | 'LLM_UNAVAILABLE';

export interface IncidentAnalysis {
  blast_radius: BlastRadiusMap; // always available (deterministic)
  report: IncidentReport | null;
  plan: RecoveryPlan | null;
  faithfulness: FaithfulnessResult | null;
  retrieved_ids: string[];
  degraded: boolean;
  routed_to_human: boolean;
  status: AnalysisStatus;
}

/** Blast-radius map derived from the operational facts in the IncidentContext — never from the model. */
export function deriveBlastRadius(ctx: IncidentContext): BlastRadiusMap {
  return BlastRadiusMapSchema.parse({
    schema_version: SCHEMA_VERSION,
    incident_id: ctx.incident_id,
    nodes: ctx.affected_hosts.map((h) => ({ host_id: h.host_id, status: h.status, role: h.role })),
    edges: ctx.topology_edges.map((e) => ({
      from_host: e.from_host,
      to_host: e.to_host,
      reachable_service: e.reachable_service,
      status: e.status,
    })),
  });
}

function queryFor(ctx: IncidentContext): string {
  const fams = ctx.telemetry_summary.families_indicated?.join(' ') ?? '';
  const signals = ctx.trigger_verdict.signals
    .filter((s) => s.fired)
    .map((s) => s.signal_type)
    .join(' ');
  return `mass encryption ransomware containment recovery ${fams} ${signals} isolate host lateral movement backup credentials notification`;
}

function buildMessages(ctx: IncidentContext, passages: PlaybookPassage[]): LLMMessage[] {
  const playbook = passages
    .map((p) => `[${p.id}] ${p.title}: ${p.content} (techniques: ${p.technique_ids.join(', ') || 'none'})`)
    .join('\n');
  const system = [
    'You are a bank SOC incident-response analyst. Produce a STRICT JSON object and nothing else.',
    'You MUST ground every claim and every recovery step in the PLAYBOOK passages provided below.',
    'Cite ONLY the passage ids given (e.g. "PB-CONTAIN-ISOLATE"). Do NOT invent passage ids or facts.',
    'If the playbook does not support a step, omit it. A safe, supported plan beats a fluent unsupported one.',
    '',
    'PLAYBOOK:',
    playbook,
    '',
    'Output JSON shape: {"summary": string, "timeline": [{"phase": string, "description": string}],',
    '"attributed_technique_ids": [string], "citations": [{"claim": string, "playbook_ref": string}],',
    '"steps": [{"order": int, "action": string, "rationale": string, "playbook_ref": string,',
    '"priority": "CRITICAL"|"HIGH"|"MEDIUM", "depends_on": [int]|null}]}',
  ].join('\n');
  const user = [
    `Incident ${ctx.incident_id} opened ${ctx.opened_at}, autonomy mode ${ctx.autonomy_mode}.`,
    `Trigger verdict: ${ctx.trigger_verdict.verdict} (confidence ${ctx.trigger_verdict.confidence}, fast_path ${ctx.trigger_verdict.fast_path}).`,
    `Fired signals: ${ctx.trigger_verdict.signals
      .filter((s) => s.fired)
      .map((s) => s.signal_type)
      .join(', ')}.`,
    `Affected hosts: ${ctx.affected_hosts.map((h) => `${h.host_id}=${h.status}`).join(', ')}.`,
    `Telemetry: ${ctx.telemetry_summary.total_files_touched} files touched; families ${ctx.telemetry_summary.families_indicated?.join(', ') ?? 'unknown'}.`,
    `Containment already taken: ${ctx.containment_actions.map((a) => a.action_type).join(', ') || 'none'}.`,
    'Produce the incident report + prioritized recovery plan as JSON.',
  ].join('\n');
  return [
    { role: 'system', content: system },
    { role: 'user', content: user },
  ];
}

/** Extract the first JSON object from a model reply (tolerates ```json fences / prose). */
export function extractJson(text: string): unknown {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  const raw = fenced ? (fenced[1] as string) : text;
  const start = raw.indexOf('{');
  const end = raw.lastIndexOf('}');
  if (start < 0 || end <= start) throw new Error('no JSON object in model output');
  return JSON.parse(raw.slice(start, end + 1));
}

export interface OrchestratorOptions {
  faithfulness?: FaithfulnessConfig;
  topK?: number;
  now?: () => string;
}

export class LLMOrchestrator {
  private llm: LLMClient;
  private opts: OrchestratorOptions;
  constructor(llm: LLMClient, opts: OrchestratorOptions = {}) {
    this.llm = llm;
    this.opts = opts;
  }

  async analyze(ctx: IncidentContext): Promise<IncidentAnalysis> {
    const blast = deriveBlastRadius(ctx);
    const passages = retrieve(queryFor(ctx), this.opts.topK ?? 6);
    const retrieved_ids = passages.map((p) => p.id);
    const now = this.opts.now ?? (() => new Date().toISOString());

    let raw: { text: string; model: string };
    try {
      raw = await this.llm.generate(buildMessages(ctx, passages), { jsonMode: true, temperature: 0.1 });
    } catch {
      // AC-FAIL-01: the model is down — degrade gracefully. Detection + containment already happened.
      return {
        blast_radius: blast,
        report: null,
        plan: null,
        faithfulness: null,
        retrieved_ids,
        degraded: true,
        routed_to_human: false,
        status: 'LLM_UNAVAILABLE',
      };
    }

    let parsed: ParsedOutput;
    try {
      parsed = extractJson(raw.text) as ParsedOutput;
    } catch {
      return {
        blast_radius: blast,
        report: null,
        plan: null,
        faithfulness: null,
        retrieved_ids,
        degraded: false,
        routed_to_human: true,
        status: 'MALFORMED_OUTPUT',
      };
    }

    const faith = checkFaithfulness(
      { summary: parsed.summary ?? '', citations: parsed.citations ?? [] },
      {
        steps: (parsed.steps ?? []).map((s, i) => ({
          ...s,
          order: s.order ?? i + 1,
        })) as RecoveryPlan['steps'],
      },
      passages,
      this.opts.faithfulness
    );

    const reportCandidate = {
      schema_version: SCHEMA_VERSION,
      incident_id: ctx.incident_id,
      generated_at: now(),
      model_id: raw.model,
      summary: parsed.summary ?? '',
      timeline: (parsed.timeline ?? []).map((t) => ({
        at: now(),
        phase: t.phase ?? '',
        description: t.description ?? '',
      })),
      attributed_technique_ids: parsed.attributed_technique_ids ?? [],
      faithfulness: {
        score: faith.score,
        passed: faith.passed,
        unsupported_claims: faith.unsupported_claims,
      },
      citations: parsed.citations ?? [],
    };
    const planCandidate = {
      schema_version: SCHEMA_VERSION,
      incident_id: ctx.incident_id,
      steps: (parsed.steps ?? []).map((s, i) => ({
        order: s.order ?? i + 1,
        action: s.action ?? '',
        rationale: s.rationale ?? '',
        playbook_ref: s.playbook_ref ?? '',
        priority: s.priority ?? 'MEDIUM',
        depends_on: s.depends_on ?? null,
      })),
      faithfulness: { score: faith.score, passed: faith.passed },
    };

    const rep = IncidentReportSchema.safeParse(reportCandidate);
    const pln = RecoveryPlanSchema.safeParse(planCandidate);
    if (!rep.success || !pln.success) {
      return {
        blast_radius: blast,
        report: null,
        plan: null,
        faithfulness: faith,
        retrieved_ids,
        degraded: false,
        routed_to_human: true,
        status: 'MALFORMED_OUTPUT',
      };
    }

    if (!faith.passed) {
      // BLOCK from authoritative use; route to a human. The artifacts are returned but flagged unfaithful.
      return {
        blast_radius: blast,
        report: rep.data,
        plan: pln.data,
        faithfulness: faith,
        retrieved_ids,
        degraded: false,
        routed_to_human: true,
        status: 'BLOCKED_LOW_FAITHFULNESS',
      };
    }
    return {
      blast_radius: blast,
      report: rep.data,
      plan: pln.data,
      faithfulness: faith,
      retrieved_ids,
      degraded: false,
      routed_to_human: false,
      status: 'OK',
    };
  }
}

interface ParsedOutput {
  summary?: string;
  timeline?: Array<{ phase?: string; description?: string }>;
  attributed_technique_ids?: string[];
  citations?: Array<{ claim: string; playbook_ref: string }>;
  steps?: Array<{
    order?: number;
    action?: string;
    rationale?: string;
    playbook_ref?: string;
    priority?: 'CRITICAL' | 'HIGH' | 'MEDIUM';
    depends_on?: number[] | null;
  }>;
}
